config/routes.rb
Rails.application.routes.draw do

  get 'contact_form/new'

  get 'contact_form/create'

  root 'sessions#new'
  
  resources :items do
    post :borrow
    post :return
		post :ownership
		post :seek
  end
  
  resources :users, except: [:new]
  get 'register', to: 'users#new'
  
  resources :schools, except: [:show]
	
	resources :password_resets
  
  resources :protocols, only: [:index, :show] do
    post :add
    post :update_value
  end
  
  get 'activity', to: 'activities#index'
	get 'report', to: 'activities#report'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
	
	get 'contact', to: 'messages#new', as: 'contact'
	post 'contact', to: 'messages#create'
	
	get 'assessment_ownership', to: 'assessment_ownerships#index'
	post 'assessment_ownership', to: 'assessment_ownerships#update'

end

app/models/item.rb
class Item < ActiveRecord::Base
    
  belongs_to :user
  belongs_to :school
  belongs_to :protocol
  has_many :exchanges
  
  validates :title, presence: true, length: { minimum: 3, maximum: 40 }
  validates :owner_location, :presence => { :message => 'Please select a school.' }
	validates :category, :presence => { :message => 'Please select a category.' }
  validates :user_id, presence: true
  
  last_protocol = ''
  
	def self.search(search, filter, category)
    if search
      self.where('title like ?', "%#{search}%")
    elsif filter
      self.where('owner_location like ?', "%#{filter}%")
		elsif category
			self.where('category like ?', "%#{category}%")
    else
      self.all
    end
  end
  
	
  #def reload_protocol(title)
  #  Protocol.where(:name => title).first_or_create!
  #  self.protocol_id = Protocol.find_by(:name => title).id
  #end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    
  before_action :set_item, only: [:edit, :update, :show, :destroy]
	before_action :set_item_from_parent, only: [:borrow, :return, :ownership, :seek]
  before_action :require_user, except: [:index]
  before_action :require_same_user, only: [:edit, :update, :destroy]


  def index
		@items = Item.search(params[:search], params[:filter], params[:category]).paginate(page: params[:page], per_page: 20).order('title ASC')
    @schools = School.all
  end


  def new
    @item = Item.new
  end


  def create
		#@protocol = Protocol.find_or_create_by(name: @item.title)
		#@item.protocol_id = @protocol.id
    #@protocol.name = @item.title
		
    @item = Item.new(item_params)
    @item.user = current_user
  
    if @item.save #&& @protocol.save
      flash[:success] = 'You have successfully created a new item.'
      redirect_to item_path(@item)
    else
      render 'new'
    end
  end
  
  
  def edit
  end


  def update
    #@item.reload_protocol(params[:item][:title])
    
    if @item.update(item_params)
      flash[:success] = "You have successfully updated #{@item.title}."
      redirect_to item_path(@item)
    else
      render 'edit'
    end
  end
  
  
  def show
    @user = User.all
    @exchanges = Exchange.where(item_id: @item).order('id DESC')
  end


  def destroy
    @item.destroy
    flash[:success] = "#{@item.title} has been deleted."
    redirect_to items_path
  end

  
  def borrow
    if @item.exchanges.any? && @item.exchanges.last.active?
      redirect_to item_path(@item)
    else
      @exchange = Exchange.new
      @exchange.borrow(current_user.id, @item)

      if @exchange.save
        flash[:success] = "You are now borrowing #{@item.title}."
        redirect_to item_path(@item)
      end
    end
  end

  def return
    @exchange = @item.exchanges.last
    @exchange.return
		
    if @exchange.save
      #UserMailer.return_confirm(@item, @item.user.email).deliver_now
      flash[:success] = "You have returned #{@item.title}."
      redirect_to item_path(@item)
    end
  end
	
	def ownership
		@item.user_id = params[:ownership]

		if @item.save
			flash[:sucess] = "#{@item.title} now belongs to #{@item.user.username}."
			redirect_to item_path(@item)
		end
	end
	
	def seek
		#UserMailer.item_request(@item, @item.user.email).deliver_now
		#flash[:success] = "You have returned #{@item.title}."
		#redirect_to item_path(@item)
	end
	

  private
    def set_item
      @item = Item.find(params[:id])
    end
  
		def set_item_from_parent
			@item = Item.find(params[:item_id])
		end	
  
    def item_params
			params.require(:item).permit(:title, :owner_location, :category)
    end
    
    
    def exchange_params
      params.require(:exchange).permit(:user_id, :lender, :item_id, :active, :borrowed_time)
    end
	
    def require_same_user
      if current_user != @item.user && !current_user.admin?
        flash[:danger] = 'You can only edit your own account.'
        redirect_to root_path
      end
    end
end

app/views/items/_form.html.erb
<div class='col-md-12'>
  <%= form_for(@item, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-3">
        <%= f.label :title %>
      </div>
      <div class="col-sm-6">
        <% if @item.errors[:title].any? %>
          <ul class="error">
            <% @item.errors[:title].each do |error| %>
              <li>*Title <%= error %></li>
            <% end %>
          </ul>
        <% end %>
				<%= f.text_field :title, class: "form-control", placeholder: "Enter an item name", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-3">
        <%= f.label :owner_location, 'Home Location' %>
      </div>
      <div class="col-sm-6">
        <% if @item.errors[:owner_location].any? %>
          <ul class="error">
            <% @item.errors[:owner_location].each do |error| %>
              <li>*<%= error %></li>
            <% end %>
          </ul>
        <% end %>
				<%= f.collection_select :owner_location, School.where.not(name: 'Administration'), :name, :name, { include_blank: 'Select a School' }, { class: 'form-control' } %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-3">
				<%= f.label :category, 'Category' %>
      </div>
      <div class="col-sm-6">
				<% if @item.errors[:category].any? %>
          <ul class="error">
						<% @item.errors[:category].each do |error| %>
              <li>*<%= error %></li>
            <% end %>
          </ul>
        <% end %>
				<%= f.select :category, ['Assessments', 'Manuals', 'Curriculum', 'Books'], { include_blank: 'Select a Category' }, { class: 'form-control' } %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-6">
				<%= f.submit(f.object.new_record? ? 'Add Item' : 'Update Item', class: 'btn btn-success btn-lg item_submit') %>
      </div>
    </div>  
  <% end %>
</div>

app/views/items/_ownership.html.erb
<div id="ownership" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <div class="modal-content">
      <div class="modal-body">
				<h3>Change of Ownership</h3>
				<p><%= @item.title %> is currently owned by <%= @item.user.username %>.</p>
				<p>Change ownership to:</p>
        
				<%= form_tag item_ownership_path(params[:id]), :method => 'post', :enforce_utf8 => false do %>
          <div class="form-group">            
						<%= select_tag(:ownership, options_from_collection_for_select(@user, "id", "username", @item.user.id), 
													:class => 'form-control') %>
					</div>
					<div class="input-group">
						<div class="input-group-btn">
							<button type="submit" class="btn btn-success change_ownership">Change Ownership</button>
							<button type="button" class="btn btn-default cancel" data-dismiss="modal">Cancel</button>
						</div>
          </div>
        <% end %>
				
      </div>
    </div>

  </div>
</div>

app/views/items/_request.html.erb
<div id="request" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <div class="modal-content">
      <div class="modal-body">
				<h3>Request Assessment</h3>
				
				<%= form_for @message, url: contact_path do |message| %>
			
					<div class="hidden">
						<%= message.text_field :name, :value => current_user.username %>
					</div>
					<div class="hidden">
						<%= message.email_field :email, :value => current_user.email %>
					</div>

					<div class="control-label col-sm-6 col-sm-offset-3">
						<strong>From : </strong><%= current_user.username %><br />
						<strong>Subject : </strong>VCOE Inventory - Message from <%= current_user.username %>
					</div>

					<div class="form-group">
						<div class="control-label col-sm-6 col-sm-offset-3">
							<%= message.text_area :content, placeholder: 'Questions? Send a message.', rows: '5', class: 'form-control' %>
						</div>
					</div>
					<div class="form-group">
						<div class="col-sm-offset-3 col-sm-6">
							<br />
							<%= submit_tag 'Send Message', class: 'btn btn-success btn-lg item_submit' %>
						</div>
					</div> 
				<% end %>
				
      </div>
    </div>

  </div>
</div>

app/views/items/edit.html.erb
<div class="container-fluid">
  <div class='row'>
    <div align="center">
      <h1>Edit <%= @item.title %></h1>
    </div>
    <%= render 'form' %>
  </div>
</div>

app/views/items/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <% if !@items.any? %>
        <div align="center">
          <p>Your search returned no results. Please try again, or <%= link_to 'view all items', items_path %>.</p>
        </div>
      <% else %>
      
				<% if params[:category] && @items.any? %>
					<h1><%= params[:category] %></h1><br>
				<% end %>
    
        <%= form_tag items_path, :method => 'get',:enforce_utf8 => false, class: 'form-inline school_filter'  do %>
          <div class="form-group">            
						<%= select_tag(:filter, options_from_collection_for_select(@schools.where.not(name: 'Administration'), 'name', 'name', params[:filter]), :prompt => 'Filter by school', class: 'form-control input-sm') %>
            <button type="submit" class="btn btn-default form-control input-sm">Filter</button>
          </div>
        <% end %>
        
				<%= form_tag items_path, :method => 'get', :enforce_utf8 => false, class: 'form-inline category'  do %>
					<div class="form-group">            
						<%= select_tag(:category, options_for_select(['Assessments', 'Manuals', 'Curriculum', 'Books'], params[:category]), :prompt => 'Select a Category', class: 'form-control input-sm') %>
						<button type="submit" class="btn btn-default form-control input-sm">Select</button>
					</div>
				<% end %>
       
				<!-- <%= link_to 'View All', items_path, :class => '' %> -->
        
      <% end %>
      
      <% @items.each do |item| %>
        <div class="panel panel-default show_all">
          <div class="panel-body">
            <div class="left show_all_title"><%= link_to item.title, item_path(item) if logged_in? %><%= item.title if !logged_in? %></div>
            <% if item.exchanges.any? && item.exchanges.last.active? %> <span class="badge pull-right">Lent out</span> <% end %>
            <div class="clearer"></div>
          <p class="left">
						<%= item.owner_location %>
					</p>
          </div>
        </div>
      <% end %>
      <div align="center">
        <%= will_paginate @items %>
      </div>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<div class="container-fluid">
  <div class='row'>
    <div align="center">
      <h1>Add an Item</h1>
    </div>
    <%= render 'form' %>
  </div>
</div>

app/views/items/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="panel panel-default col-sm-7 col-sm-offset-1">
      <div class="panel-body">
        <h1 class="left"><%= @item.title %></h1>
        <% if logged_in? && (@item.user == current_user || current_user.admin?) %>
          <div class="dropdown pull-right">
            <button class="dropdown-toggle edit_item_dropdown" type="button" data-toggle="dropdown">
              Edit <span class="glyphicon glyphicon-cog"></span>
            </button>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit #{@item.title}", edit_item_path(@item) %></li>
							<% if current_user.admin? %>
								<li><a href="" data-toggle="modal" data-target="#ownership">Change Ownership</a></li>
							<% end %>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Delete #{@item.title}", item_path(@item), method: :delete, data: { confirm: "Are you sure you want to delete #{@item.title}?" } %></li>
            </ul>
          </div>
        <% end %>
        <div class="clear"></div>
        <p>Home Location: <%= @item.owner_location %></p>
        <p>Owned by: <%= link_to @item.user.username, user_path(@item.user) %></p>
				<% if @item.category %>
					<p>Category: <%= @item.category %></p>
				<% end %>
        <a href="" class="view_history">View History</a>
        <ul id="exchange_history">
          <hr>
          <% if @exchanges.any? %>
            <% @exchanges.each do |exchange| %>
              <li>
                Borrowed by <%= exchange.user.username %> on <%= exchange.borrowed_time %> <br>
                <% if exchange.active == false %>
                  Returned <%= exchange.return_time %>.
                <% end %>
              </li>
            <% end %>
          <% else %>
            <p>No history to show..</p>
          <% end %>
        </ul>
        
      </div>
    </div>
    
    <div class="panel panel-default col-sm-3 side">
      <div class="panel-body">
        
				<%= button_to "Borrow", item_borrow_path(@item.id), class: 'btn btn-success borrow' if !@item.exchanges.any? || !@item.exchanges.last.active? %>
        <% if @item.exchanges.any? && @item.exchanges.last.user == current_user %>
          <%= button_to "Return", item_return_path(@item.id), class: 'btn btn-warning borrow' if @item.exchanges.last.active? %>
        <% else %>
          <%= button_to "Return", item_return_path(@item.id), class: 'btn btn-warning borrow', :disabled => true if @item.exchanges.any? && @item.exchanges.last.active? %>
        <% end %>

        <% if @item.exchanges.any? && @item.exchanges.last.active? %>
          <hr>
          <p>Lent to <%= link_to @item.exchanges.last.user.username, user_path(@item.exchanges.last.user) %>
						(<%= @item.exchanges.last.user.location %>)<br>
          on <%= @item.exchanges.last.borrowed_time %>.</p>
        <% end %>
        
        <!--
        <hr>
				<a href="" data-toggle="modal" data-target="#request">Request <%= @item.title %></a>
     		-->
      </div>
    </div>
    
  </div>
  
</div>

<%= render 'ownership' %>