config/routes.rb
Rails.application.routes.draw do

  get 'contact_form/new'

  get 'contact_form/create'

  root 'sessions#new'
  
  resources :items do
    post :borrow
    post :return
		post :ownership
		post :seek
  end
  
  resources :users, except: [:new]
  get 'register', to: 'users#new'
  
  resources :schools, except: [:show]
	
	resources :password_resets
  
  resources :protocols, only: [:index, :show] do
    post :add
    post :update_value
  end
  
  get 'activity', to: 'activities#index'
	get 'report', to: 'activities#report'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
	
	get 'contact', to: 'messages#new', as: 'contact'
	post 'contact', to: 'messages#create'
	
	get 'assessment_ownership', to: 'assessment_ownerships#index'
	post 'assessment_ownership', to: 'assessment_ownerships#update'

end

app/models/school.rb
class School < ActiveRecord::Base
  
  has_many :items
  
  validates :name, presence: true, length: { minimum: 3, maximum: 20 }
    
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
   
   before_action :set_school, only: [:edit, :update, :destroy]
   before_action :require_admin
   
   def index
     @schools = School.all.order('name ASC')
   end
    
  def new
    @school = School.new
  end
  
  def create
    @school = School.new(school_params)
    if @school.save
      flash[:success] = 'You have successfully added a new school.'
      redirect_to schools_path
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @school.update(school_params)
      flash[:success] = "You have successfully updated #{@school.name}"
      redirect_to schools_path
    else
      render 'edit'
    end
    
  end
  
  def destroy
    deleted_school = @school.name
    @school.destroy
    flash[:success] = "You have successfully deleted #{deleted_school}"
    redirect_to schools_path
  end



  private
    def school_params
      params.require(:school).permit(:name)
    end
    
    def set_school
      @school = School.find(params[:id])
    end

end

app/views/schools/_form.html.erb
<div class='col-md-12'>
  <%= form_for(@school, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-3">
        <%= f.label :name, 'School Name' %>
      </div>
      <div class="col-sm-6">
        <% if @school.errors[:name].any? %>
          <ul class="error">
            <% @school.errors[:name].each do |error| %>
              <li>*School name <%= error %></li>
            <% end %>
          </ul>
        <% end %>
        <%= f.text_field :name, class: "form-control", placeholder: "Enter a school name", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-6">
        <%= f.submit(f.object.new_record? ? 'Add School' : 'Update School', class: 'btn btn-success btn-lg item_submit') %>
      </div>
    </div>  
  <% end %>
</div>

app/views/schools/edit.html.erb
<div class="container-fluid">
  <div class='row'>
    <div align="center">
      <h1>Edit <%= @school.name %></h1>
    </div>
    <%= render 'form' %>
  </div>
</div>

app/views/schools/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <div align="center">
        <h1>Schools</h1>
      </div>
      <%= link_to 'Add a School', new_school_path %><br /><br />
      
      <% @schools.each do |school| %>
        <div class="panel panel-default show_all">
          <div class="panel-body">
            <div class="left show_all_title"><%= school.name %></div>
            <div class="dropdown pull-right">
              <button class="dropdown-toggle edit_item_dropdown" type="button" data-toggle="dropdown">
                Edit <span class="glyphicon glyphicon-cog"></span>
              </button>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit #{school.name}", edit_school_path(school) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Delete #{school.name}", school_path(school), method: :delete, data: { confirm: "Are you sure you want to delete #{school.name}?" } %></li>
              </ul>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/schools/new.html.erb
<div class="container-fluid">
  <div class='row'>
    <div align="center">
      <h1>Add a New School</h1>
    </div>
    <%= render 'form' %>
  </div>
</div>