config/routes.rb
Rails.application.routes.draw do

  get 'contact_form/new'

  get 'contact_form/create'

  root 'sessions#new'
  
  resources :items do
    post :borrow
    post :return
		post :ownership
		post :seek
  end
  
  resources :users, except: [:new]
  get 'register', to: 'users#new'
  
  resources :schools, except: [:show]
	
	resources :password_resets
  
  resources :protocols, only: [:index, :show] do
    post :add
    post :update_value
  end
  
  get 'activity', to: 'activities#index'
	get 'report', to: 'activities#report'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
	
	get 'contact', to: 'messages#new', as: 'contact'
	post 'contact', to: 'messages#create'
	
	get 'assessment_ownership', to: 'assessment_ownerships#index'
	post 'assessment_ownership', to: 'assessment_ownerships#update'

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
	
	before_action :set_exchanges
	
  def index
  end
  
	def report
		report = [ (params[:view_by] || "") + "\n", 
			"Report generated on " + Time.zone.now.to_s + "\n", 
			"-----------------------------------------\n\n" ]
		
		@exchanges.each do |exchange|
			report.push("** " + exchange.item_title + " **\n")
			report.push("Borrowed: " + exchange.borrowed_time + ", " + exchange.user.username + "\n")
			report.push("Returned: " + (exchange.return_time || "___________") + "\n\n")
		end
		send_data report.join(''), :filename => 'report.txt'
	end
	
	
	private
	
		def set_exchanges
			if params[:view_by] == 'pending_return'
				@exchanges = Exchange.where(active: true).order('item_title ASC')
			else
				@exchanges = Exchange.all.order('item_title ASC, id ASC')
			end
		end
end

app/views/activities/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <div align="center">
        <h1>Activity</h1>
      </div>
      
      <%= form_tag activity_path, :method => 'get', :enforce_utf8 => false, class: 'form-inline activity'  do %>
        <div class="form-group">            
          <button type="submit" value="" class="btn btn-default form-control input-sm">All</button>
          <button type="submit" value="pending_return" class="btn btn-default form-control input-sm" name="view_by">Pending Return</button>
        </div>
      <% end %>
			<%= form_tag report_path, :method => 'get', :enforce_utf8 => false, class: 'form-inline save_report right'  do %>
        <div class="form-group">   
					<%= hidden_field_tag :view_by, params[:view_by] %>
          <button type="submit" value="" class="btn btn-default form-control input-sm">Save Report <span class="glyphicon glyphicon-file"></span></button>
        </div>
      <% end %>
      <div class="clear"></div>
			
      <% @exchanges.each do |exchange| %>
        ** <strong><%= exchange.item_title %></strong> **<br />
        Borrowed: <%= exchange.borrowed_time %>, <%= exchange.user.username %><br />
        Returned: <%= (exchange.return_time || '____________') %><br />
        =========================<br />
      <% end %>
    </div>
  </div>
</div>