config/routes.rb
Rails.application.routes.draw do

  get 'contact_form/new'

  get 'contact_form/create'

  root 'sessions#new'
  
  resources :items do
    post :borrow
    post :return
		post :ownership
		post :seek
  end
  
  resources :users, except: [:new]
  get 'register', to: 'users#new'
  
  resources :schools, except: [:show]
	
	resources :password_resets
  
  resources :protocols, only: [:index, :show] do
    post :add
    post :update_value
  end
  
  get 'activity', to: 'activities#index'
	get 'report', to: 'activities#report'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
	
	get 'contact', to: 'messages#new', as: 'contact'
	post 'contact', to: 'messages#create'
	
	get 'assessment_ownership', to: 'assessment_ownerships#index'
	post 'assessment_ownership', to: 'assessment_ownerships#update'

end

app/views/common/_messages.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <% flash.each do |name, msg| %>
    
    <div class="alert alert-warning alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= msg %>
    </div>
    <% end %>
  </div>
</div>

app/views/common/_navigation.html.erb
<div class="container-fluid top">
  <div id="top">
    <%= link_to image_tag('/images/VCOELogo_sm.png'), root_path %>
    <div class="user_greeting">
      <% if logged_in? %>
        <ul class="user_dropdown right">
          <li class="dropdown pull-right">
            <a href="#" class="dropdown-toggle user_settings" data-toggle="dropdown" role="button">User Settings <span class="glyphicon glyphicon-cog"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'View Profile', user_path(current_user) %></li>
              <li><%= link_to 'Edit Profile', edit_user_path(current_user) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
            </ul>
          </li>
        </ul>
        <div class="hello right">
          <span class="salud right">
            Hello, <%= current_user.username %>!
            <% if current_user.admin? %> - Admin
            <% end %>
          </span>
          <span class="glyphicon glyphicon-user right greeting"></span>
        </div>
      <% else %>
        <%= link_to 'Register', register_path, class: 'right not_logged_in' %>
        <%= link_to 'Log In', login_path, class: 'right not_logged_in' %>
      <% end %>
    </div>
  </div>
</div>


<nav class="navbar navbar-inverse">
  <div class="container-fluid">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Items <span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><%= link_to 'Add An Item', new_item_path if logged_in? %></li>
						<li role="separator" class="divider"></li>
						<li><%= link_to 'View All Items', items_path %></li>
					</ul>
				</li>
				
				<!--<li><%= link_to 'Protocols', protocols_path if logged_in? %></li>-->
				<li><%= link_to 'View Users', users_path if logged_in? %></li>
				
        <% if logged_in? && current_user.admin? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Admin <span class="caret"></span></a>
            <ul class="dropdown-menu">
							<li><%= link_to 'Item Ownership', assessment_ownership_path %></li>
              <li><%= link_to 'Schools', schools_path %></li>
              <li><%= link_to 'Activity', activity_path %></li>
            </ul>
          </li>
        <% end %>
				
				<li><%= link_to 'Help/Contact', contact_path if logged_in? %></li>
      </ul>
      
      <%= form_tag items_path, :method => 'get', :enforce_utf8 => false, class: 'navbar-form navbar-right'  do %>
        <div class="input-group">
					<%= text_field_tag :search, params[:search], :placeholder => 'Search items.. ' , class: 'form-control' %>
        <span class="input-group-btn">
          <%= button_tag(type: 'submit', :name => nil, class: "btn btn-default") do %>
            <span class="glyphicon glyphicon-search"></span>
          <% end %>
        </span>
        </div>
      <% end %>
      
    </div>
  </div>
</nav>